apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nginx-conf
    files:
      - nginx/config/nginx.conf

resources:
  - nginx/nginx-deploy.yaml
  - nginx/nginx-service.yaml
  - redis1/redis1-deploy.yaml
  - redis1/redis1-service.yaml
  - redis2/redis2-deploy.yaml
  - redis2/redis2-service.yaml
